apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: proxy-poc
data:
  traefik.toml: |
      debug = true
      logLevel = "DEBUG"
      defaultentrypoints = ["http"]
      [entryPoints.http]
      address = ":8080"
      [entryPoints.healthz]
      address = ":8081"
      [entryPoints.auth_api]
      address = ":8099"
      [api]
      dashboard = true
      entrypoint = "auth_api"
      [wss]
      protocol = "http"
      [entryPoints.auth_api.auth.basic]
      # abc:123
      users = [ "abc:$apr1$a4hgl/yM$Dq4i/FSkAzOC7Uj55xEMD/", ]
      [file]
      filename = "/watched/rules.toml"
      watch = true
      [ping]
      entryPoint = "healthz"
