apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-proxy
  namespace: proxy-poc
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-proxy
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-proxy
  namespace: proxy-poc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traefik-proxy
subjects:
- kind: ServiceAccount
  name: traefik-proxy
