---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: proxy-poc
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - name: admin
      protocol: TCP
      port: 8099
      targetPort: 8099
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: api-https
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
