apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: Jupyter notebook image with minimal dependency set to start experimenting with Jupyter environment.
    opendatahub.io/notebook-image-name: Minimal Python
    opendatahub.io/notebook-image-url: https://github.com/thoth-station/s2i-minimal-notebook
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
  name: s2i-minimal-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      opendatahub.io/notebook-python-dependencies: '[{"name":"JupyterLab","version": "3.0.14"}, {"name": "Notebook","version": "6.3.0"}]'
      opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8.3"}]'
      openshift.io/imported-from: quay.io/modh/odh-minimal-notebook-container
    from:
      kind: DockerImage
      name: quay.io/odh-jupyterhub/s2i-minimal-notebook:3.6
    name: latest
    referencePolicy:
      type: Local
